services:
  send2ereader:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    container_name: send2ereader
    hostname: send2ereader
    image: ghcr.io/gcaguilar/send2ereader:latest
    restart: unless-stopped
    ports:
      - 3001:3001
